version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install --group docs .

sphinx:
  configuration: docs/conf.py
