[sampling_options]
fov_center_ra = "17:45:40"
fov_center_dec = "-29:00:28.2"
fov_size = 0.00018382
corr_int_time = 10.0
scan_start = "2016:95:00:00:00"
scan_duration = 300
scans = 72
interval_length = 1200
channel = "227297:4096"