[sampling_options]
mode = "full"
device = "cpu"
layout = "vla"
img_size = 128
fov_center_ra = [100, 110]
fov_center_dec = [30, 40]
fov_size = 100
corr_int_time = 30.0
scan_start = ["16-01-2020 00:04:01", "16-01-2020 08:59:59"]
scan_duration = [60, 90]
num_scans = [1, 2]
scan_separation = 360
ref_frequency = 15.21e9
frequency_offsets = [0e8, 0.8e8, 1.44e8, 2.08e8]
bandwidths = [6.4e7, 6.4e7, 6.4e7, 6.4e7]
noisy = false
corrupted = false
sensitivity_cut = false
cut_value = 1e-6

[bundle_options]
in_path = "skies/"
out_path_fits = "build/uvfits"
out_path_gridded = "build/gridded"
num_test_images = 500
bundle_size = 100
train_valid_split = 0.2
grid_size = 128
amp_phase = false
